# file: roles/nginx/tasks/main.yml
---
- name: Ensure nginx is installed
  yum:
    name: 'nginx'
    state: 'installed'

- name: Ensure nginx start on boot
  service:
    name: 'nginx'
    state: 'started'
    enabled: yes
